# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import resources
import mysql.connector
import requests
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QPixmap, QImage
from PyQt5 import QtCore, QtGui, QtWidgets

mydb = mysql.connector.connect(option_files='my.conf')
 

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        MainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/Simple_PySide_Base-master/icons/20x20/cil-3d.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color:rgb(11, 89, 185);\n"
"")
        MainWindow.setIconSize(QtCore.QSize(20, 20))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_left_menu = QtWidgets.QFrame(self.centralwidget)
        self.frame_left_menu.setGeometry(QtCore.QRect(9, 9, 1280, 70))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_left_menu.sizePolicy().hasHeightForWidth())
        self.frame_left_menu.setSizePolicy(sizePolicy)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(1280, 70))
        self.frame_left_menu.setMaximumSize(QtCore.QSize(1280, 70))
        self.frame_left_menu.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_left_menu.setStyleSheet("background-color: rgb(27, 29, 35);")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_menus = QtWidgets.QFrame(self.frame_left_menu)
        self.frame_menus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menus.setObjectName("frame_menus")
        self.layout_menus = QtWidgets.QVBoxLayout(self.frame_menus)
        self.layout_menus.setContentsMargins(0, 0, 0, 0)
        self.layout_menus.setSpacing(0)
        self.layout_menus.setObjectName("layout_menus")
        self.verticalLayout_5.addWidget(self.frame_menus, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_toggle_menu_4 = QtWidgets.QPushButton(self.frame_left_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_toggle_menu_4.sizePolicy().hasHeightForWidth())
        self.btn_toggle_menu_4.setSizePolicy(sizePolicy)
        self.btn_toggle_menu_4.setStyleSheet("QPushButton {\n"
"    background-image: url(:/newPrefix/Simple_PySide_Base-master/icons/20x20/cil-3d.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    border: none;\n"
"    background-color: rgb(27, 29, 35);\n"
"}\n"
"")
        self.btn_toggle_menu_4.setText("")
        self.btn_toggle_menu_4.setObjectName("btn_toggle_menu_4")
        self.horizontalLayout.addWidget(self.btn_toggle_menu_4)
        self.btn_toggle_menu = QtWidgets.QPushButton(self.frame_left_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_toggle_menu.sizePolicy().hasHeightForWidth())
        self.btn_toggle_menu.setSizePolicy(sizePolicy)
        self.btn_toggle_menu.setStyleSheet("QPushButton {\n"
"    background-image: url(:/newPrefix/Simple_PySide_Base-master/icons/20x20/cil-home.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    border: none;\n"
"    background-color: rgb(27, 29, 35);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_toggle_menu.setText("")
        self.btn_toggle_menu.setObjectName("btn_toggle_menu")
        self.horizontalLayout.addWidget(self.btn_toggle_menu)
        self.btn_toggle_menu_3 = QtWidgets.QPushButton(self.frame_left_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_toggle_menu_3.sizePolicy().hasHeightForWidth())
        self.btn_toggle_menu_3.setSizePolicy(sizePolicy)
        self.btn_toggle_menu_3.setStyleSheet("QPushButton {\n"
"    background-image: url(:/newPrefix/Simple_PySide_Base-master/icons/20x20/cil-comment-bubble.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    border: none;\n"
"    background-color: rgb(27, 29, 35);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_toggle_menu_3.setText("")
        self.btn_toggle_menu_3.setObjectName("btn_toggle_menu_3")
        self.horizontalLayout.addWidget(self.btn_toggle_menu_3)
        self.btn_toggle_menu_2 = QtWidgets.QPushButton(self.frame_left_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_toggle_menu_2.sizePolicy().hasHeightForWidth())
        self.btn_toggle_menu_2.setSizePolicy(sizePolicy)
        self.btn_toggle_menu_2.setStyleSheet("QPushButton {\n"
"    background-image: url(:/newPrefix/Simple_PySide_Base-master/icons/20x20/cil-lightbulb.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    border: none;\n"
"    background-color: rgb(27, 29, 35);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_toggle_menu_2.setText("")
        self.btn_toggle_menu_2.setObjectName("btn_toggle_menu_2")
        self.horizontalLayout.addWidget(self.btn_toggle_menu_2)
        self.btn_toggle_menu_5 = QtWidgets.QPushButton(self.frame_left_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_toggle_menu_5.sizePolicy().hasHeightForWidth())
        self.btn_toggle_menu_5.setSizePolicy(sizePolicy)
        self.btn_toggle_menu_5.setStyleSheet("QPushButton {\n"
"    background-image: url(:/newPrefix/Simple_PySide_Base-master/icons/20x20/cil-menu.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    border: none;\n"
"    background-color: rgb(27, 29, 35);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_toggle_menu_5.setText("")
        self.btn_toggle_menu_5.setObjectName("btn_toggle_menu_5")
        self.horizontalLayout.addWidget(self.btn_toggle_menu_5)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.ViewProfile = QtWidgets.QLabel(self.centralwidget)
        self.ViewProfile.setGeometry(QtCore.QRect(40, 120, 256, 192))
        self.ViewProfile.setObjectName("ViewProfile")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(310, 120, 331, 191))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.name = QtWidgets.QLabel(self.layoutWidget)
        self.name.setObjectName("name")
        self.verticalLayout.addWidget(self.name)
        self.age = QtWidgets.QLabel(self.layoutWidget)
        self.age.setObjectName("age")
        self.verticalLayout.addWidget(self.age)
        self.email = QtWidgets.QLabel(self.layoutWidget)
        self.email.setObjectName("email")
        self.verticalLayout.addWidget(self.email)
        self.degrees = QtWidgets.QLabel(self.layoutWidget)
        self.degrees.setObjectName("degrees")
        self.verticalLayout.addWidget(self.degrees)
        self.fa = QtWidgets.QLabel(self.layoutWidget)
        self.fa.setObjectName("fa")
        self.verticalLayout.addWidget(self.fa)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionTEST = QtWidgets.QAction(MainWindow)
        self.actionTEST.setObjectName("actionTEST")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "UBU"))
        self.name.setText(_translate("MainWindow", "TextLabel"))
        self.age.setText(_translate("MainWindow", "TextLabel"))
        self.email.setText(_translate("MainWindow", "TextLabel"))
        self.degrees.setText(_translate("MainWindow", "TextLabel"))
        self.fa.setText(_translate("MainWindow", "TextLabel"))
        self.actionTEST.setText(_translate("MainWindow", "TEST"))

    def setuser(self,valuse1,userid):
        mycursor = mydb.cursor()
        sql = 'select * from user_infomations where user_infomations.ID = (%s)'%(userid)
        mycursor.execute(sql)
        a = mycursor.fetchone()
        a = list(a)
        print (a)
        url_picture = 'https://storage.googleapis.com/picture-data/img{:s}.jpg'.format(a[7])
        image = QImage()
        image.loadFromData(requests.get(url_picture).content)
        #pixmap = QPixmap('https://console.cloud.google.com/storage/browser/picture-data/img{:s}.jpg'.format(a[7]))
        pixmap = QPixmap(image)
        smaller = pixmap.scaled(400,250, Qt.KeepAspectRatio, Qt.FastTransformation)
        self.ViewProfile.setPixmap(smaller)
        self.name.setText('Name {:}'.format(valuse1[0]))
        self.age.setText('Age {:}'.format(valuse1[1]))
        self.email.setText('Email {:}'.format(valuse1[2]))
        mycursor2 = mydb.cursor()
        sqlfa = """SELECT describe1 FROM user_faculty 
                join user_infomations 
                on user_faculty.faculty = user_infomations.faculty 
                where user_infomations.faculty = (%s)"""%(a[6])
        mycursor2.execute(sqlfa)
        fa = mycursor2.fetchone()
        fa = list(fa)
        self.fa.setText(fa[0])
        mycursor3 = mydb.cursor()
        sqlfa = """SELECT describe2 FROM user_faculty 
                join user_infomations 
                on user_faculty.degrees = user_infomations.degrees
                where user_infomations.degrees = (%s)"""%(a[5])
        mycursor3.execute(sqlfa)
        de = mycursor3.fetchone()
        de = list(de)
        self.degrees.setText(de[0])



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
